name: goreleaser

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      ARCH: "amd64"
      DOCKER_DEV_ACCOUNT: "ghcr.io/${{ github.repository_owner }}"
      DOCKER_IMAGE_TAG: ${{ github.ref_name }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run:
          make docker-cilium-image